version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 4865
      MYSQL_DATABASE: datn_ecommerce
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 4865
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build:
      dockerfile: Dockerfile
    container_name: springboot-app
    depends_on:
      - db
    ports:
      - "8087:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/datn_ecommerce?sessionVariables=sql_mode=''
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 4865
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_PROTOCOL: smtp
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      BEZKODER_APP_JWTSECRET: bezKoderSecretKey
      BEZKODER_APP_JWTEXPIRATIONMS: 86400000
      FILE_UPLOAD_DIR: static/images/product/
      IMAGE_FILE_UPLOAD_DIR: static/images/other/
      PDF_FILE_DOWNLOAD_DIR: static/invoices/
      GOOGLE_APP_ID: 4324503554-bt9sjojk5ml20lo40oq7tau8uni5pp5c.apps.googleusercontent.com
      GOOGLE_APP_SECRET: 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
      GOOGLE_REDIRECT_URI: http://localhost:8080/oauth2/google
      GOOGLE_LINK_GET_TOKEN: https://accounts.google.com/o/oauth2/token
      GOOGLE_LINK_GET_USER_INFO: https://www.googleapis.com/oauth2/v1/userinfo?access_token=
      FACEBOOK_APP_ID: 677457713240896
      FACEBOOK_APP_SECRET: da01eae4cd942b51d492cea5c709323a
      FACEBOOK_REDIRECT_URI: https://afcb-123-24-236-162.ngrok.io/oauth2/facebook
      FACEBOOK_LINK_GET_TOKEN: https://graph.facebook.com/oauth/access_token?client_id=%s&client_secret=%s&redirect_uri=%s&code=%s

  # admin-frontend:
  #   build:
  #     context: ./admin-frontend
  #     dockerfile: Dockerfile
  #   container_name: admin-app
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - backend

  # client-frontend:
  #   build:
  #     context: ./client-frontend
  #     dockerfile: Dockerfile
  #   container_name: client-app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

  # python-service:
  #   build:
  #     context: ./python-service
  #     dockerfile: Dockerfile
  #   container_name: python-app
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db

volumes:
  db-data:
